### ISSUE TITLE
tello-tracking.py startet nicht

### ISSUE THREAD

**Issue by andreSai** [msoftware/tello-tracking#1]
Hallo, ich habe ein frisches System (am 20.12.2021) nach Anleitung in der make 6/2021 auf meinem Jetson-nano installiert, lief problemlos durch, jedoch wirft Tello-tracking.py einen Fehler:
Traceback (most recent call last):
  File "./tello-tracking.py", line 13, in <module>
    from utils.mtcnn import TrtMtcnn
  File "/home/asjetson/tello/tello-tracking/utils/mtcnn.py", line 6, in <module>
    import pytrt
ImportError: libnvinfer.so.7: cannot open shared object file: No such file or directory

**Comment by michaelholoubek** [comment]
Hi, das selbe Problem tritt auch bei mir auf. Die Datei libnvinfer.so.7 existiert auch nicht sondern nur die libnvinfer.so.8. Es ist also ein Versionsproblem, aber ich weiß leider nicht was hier, wo anzupassen wäre um die ältere Version zu erstellen, oder die neuere zu verwenden.

**Comment by Hagelstein** [comment]
Huhu... gleiches Problem:
michael@michael-desktop:~/tello-tracking$ ./tel*
Traceback (most recent call last):
  File "./tello-tracking.py", line 13, in <module>
    from utils.mtcnn import TrtMtcnn
  File "/home/michael/tello-tracking/utils/mtcnn.py", line 6, in <module>
    import pytrt
ImportError: libnvinfer.so.7: cannot open shared object file: No such file or directory

Nur...wie korrigiert man das?

**Comment by andreSai** [comment]
ich habe mir mit einem Link beholfen

 ***@***.***:/usr/lib/aarch64-linux-gnu$ sudo ln -s libnvinfer.so libnvinfer.so.7

danach hats funktioniert.  Ich habe die Sache aber nur mal ausprobiert, wie zu erwarten lief das Ganze nicht sonderlich stabil, ist eher ein, wenn auch sehr interessanter, Demonstrator.

Ich hoffe, das hilft Dir, Gruss André

Von meinem iPad gesendet

**Comment by Hagelstein** [comment]
Vielen Dank! Hab es nochmal versucht.... bin erst in das Verzeichnis gegangen und habe dort den Befehl ausgeführt....jetzt startet es :-)

Also erst nach
 usr/lib/aarch64-linux-gnu

Und dort

sudo ln -s libnvinfer.so libnvinfer.so.7
